name: Desplegando yaml APIGW
on:
  push:
    branches:
     - main
    paths:
      - 'api.yml'
  workflow_dispatch:

env:
  ID_API: yhvtgvwqt6
  aws_account_id: 871340136996

jobs:
  Copia_swagger:
    runs-on: ubuntu-latest
    steps:
    - name: Copiando fichero yaml
      uses: actions/checkout@v2

  Despliegue_apigw_DEV:
    needs: Copia_swagger
    runs-on: ubuntu-latest
    #if: contains(github.event.head_commit.message, 'api-update')
    steps:
    - name: Configurando credenciales para AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}        
    - name: list
      run: ls -la
    - name: Aplicando yaml DEV
      run: |
        ls
        aws apigateway put-rest-api --rest-api-id ${ID_API} --mode overwrite --body "fileb://api.yml"
        aws apigateway create-deployment --rest-api-id ${ID_API} --region us-east-1  --stage-name dev --stage-description 'Development Stage' --description 'Deployment to the dev stage'